### ISSUE TITLE
Potential trademark violation (Alice Os)

### ISSUE THREAD

**Issue by dginu85** [TheAngelReturns/aliceos-docs#2] opened 2019-01-14 22:34 UTC
Alice Os, AliceOs is copyright of one multimedia.
Remove this.

**Comment by alicerunsonfedora** [comment] 2019-01-15 03:16
Duplicate of ProjectAliceDev/aliceos#39

**Closed as completed by alicerunsonfedora** 2019-01-15 03:16 UTC
Labels: duplicate, question

**Comment by sr229** [comment] 2019-01-21 09:31
Locking this down to prevent reopening
